### ISSUE TITLE
Throwing a Zero Status Code When Error Occurred

### ISSUE THREAD

**Issue by sbdchd** [kentcdodds/prettier-eslint-cli#10]
Currently, when prettier-eslint-cli encounters an error, it throws an `0` status code, when it should be throwing a non-zero exit code.

**Comment by kentcdodds** [comment]
Do you mind creating a pull request to fix that? [makeapullrequest.com](http://makeapullrequest.com)

**Comment by sbdchd** [comment]
I think adding [`process.exit(1)`][1] at https://github.com/kentcdodds/prettier-eslint-cli/blob/master/src/format-files.js#L169 should do the trick.

[1]: https://nodejs.org/api/process.html#process_event_exit

**Comment by kentcdodds** [comment]
Thanks for your patience @sbdchd, I've been thinking about this and I'd prefer to avoid `process.exit` calls, but we could do `process.exitCode = 1`. Also I'd prefer to not put it in the logError function but instead put it after the function call in the specific places it we want to have things fail. Thoughts?

**Comment by kentcdodds** [comment]
This should be fixed now. Let me know if it's not :)
