### ISSUE TITLE
What to do with "failure formatting 12 files with prettier-eslint"

### ISSUE THREAD

**Issue by oncletom** [kentcdodds/prettier-eslint-cli#11]
Hello,

thanks a lot for this project :-)

A small question because I am unsure about what action to take after seeing that I have 12 files which fails to be written/formatted. I can't see any detail on the errors and I am not sure either if I shall expect eslint errors to be forwarded by `prettier-eslint-cli`.

This is the command I run:

```bash
prettier-eslint --write --log chapter*/**/*.js
```

Thanks for your help :-)

cc @DirtyF

**Comment by kentcdodds** [comment]
Try updating and running that again...

**Comment by DirtyF** [comment]
updated to latest npm packages:

```diff
~/code/nodebook prettier-examples*
❯ git diff
modified: package.json
@ package.json:36 @
-- "prettier-eslint": "^3.0.2",
-- "prettier-eslint-cli": "^1.1.0",
++ "prettier-eslint": "^3.0.3",
++ "prettier-eslint-cli": "^1.1.1",
```

@kentcdodds doesn't change the message displayed about failures:

```sh
~/code/nodebook prettier-examples*
❯ npm test

> nodebook@0.4.0 test /Users/frank/code/nodebook
> exit 0


> nodebook@0.4.0 posttest /Users/frank/code/nodebook
> npm run format && npm run lint


> nodebook@0.4.0 format /Users/frank/code/nodebook
> prettier-eslint --write chapter**/**/*.js

success formatting 1 file with prettier-eslint
failure formatting 7 files with prettier-eslint
33 files were unchanged

> nodebook@0.4.0 lint /Users/frank/code/nodebook
> eslint --ignore-path .gitignore --fix '**/*.js'

```

**Comment by kentcdodds** [comment]
Hmmm... I think we need better logging.

One thing I should mention is that you should quote your globs: `prettier-eslint --write --log "chapter**/**/*.js"`. Otherwise your terminal will expand the glob before it gets to prettier-eslint (which can have unexpected results). (Incidentally if you want to add that to the docs that'd be super!)

If you want to do some digging to figure out what's going on, that'd be great. You could start by jumping into your `node_modules/prettier-eslint/dist/index.js` and adding console.logs in places to see what's going on. Then maybe we can add more places to log more useful info.

**Comment by DirtyF** [comment]
@kentcdodds thanks, much better with the quotes indeed 😖 

```sh
~/code/nodebook prettier-examples*
❯ npm run format

> nodebook@0.4.0 format /Users/frank/code/nodebook
> prettier-eslint --write --log 'chapter*/**/*.js'

success formatting 89 files with prettier-eslint
42 files were unchanged
```

PR for documentation on its way ✍️

**Comment by oncletom** [comment]
Ah funny, I tried with the quotes and got no results so I thought the right way to go was without the quotes.

Thanks @DirtyF and @kentcdodds :-)

**Comment by kentcdodds** [comment]
Yeah, there was a bug where `prettier-eslint` would consider whatever you put after `--write` as the value of `write` which made no sense. That's been fixed. So does this solve the problem?

**Comment by DirtyF** [comment]
@kentcdodds problem solved, yes.

FYI we encounter an edge case with inline comments for JS code snippets annotations in asciidoctor, but that would be a separate issue. Thanks for your feedback.
