### ISSUE TITLE
Unable to find config

### ISSUE THREAD

**Issue by mvolkmann** [kentcdodds/prettier-eslint-cli#29]
I followed the example of installing prettier-eslint-cli as a dev dependency, adding a `format` script in `package.json`, and I have a `.eslintrc.json` file in the root directory of my project, but when I run `npm run format` I get this:
````
> prettier-eslint "src/**/*.js"

prettier-eslint [ERROR]: Unable to find config
prettier-eslint [ERROR]: Unable to find config
failure formatting 2 files with prettier-eslint
````
I must be missing a step.

**Comment by kentcdodds** [comment]
Hmm... That's odd... Try adding `--log-level=debug`.

**Comment by mvolkmann** [comment]
Not much more information.
````
> prettier-eslint --log-level=debug "src/**/*.js"

prettier-eslint [DEBUG]: getting eslint config for file at "src/App.js"
prettier-eslint [ERROR]: Unable to find config
prettier-eslint [DEBUG]: getting eslint config for file at "src/index.js"
prettier-eslint [ERROR]: Unable to find config
failure formatting 2 files with prettier-eslint
````
Does that mean it can't find the ESLint configuration file?
I have a `.eslintrc.json` file in the directory where the `src` directory resides.

**Comment by kentcdodds** [comment]
Hmmm... Try `--log-level=trace`

**Comment by mvolkmann** [comment]
I'm trying to debug this. Can you tell me where the CLIEngine class is defined? That seems to be where things go wrong. Is that something defined by ESLint rather than by prettier-eslint?

**Comment by kentcdodds** [comment]
That's ESLint's node API. http://eslint.org/docs/developer-guide/nodejs-api

**Comment by mvolkmann** [comment]
Wow! That took a lot of digging!
I think I found the problem, but of course I could be wrong.
I believe this is a bug in ESLint.

Look at this file: https://github.com/eslint/eslint/blob/master/lib/config/config-file.js
In the function `localPackageJSONConfigFile` see this line:
https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L178
Then look at the `loadJSONConfigFile` function here:
https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L120
That parses a `.eslintrc.json` file. It works fine with mine and then it returns that as an object created by parsing the JSON.
But this line: https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L178
expects the object returned to have a property named `eslintConfig` that holds the object.
The return value IS the object. It isn't an object with an `eslintConfig` property.

What do you think? Is this a bug?

**Comment by kentcdodds** [comment]
Sounds like it's either an ESLint bug or your config is wrong. I'd recommend you make a minimal reproduction repository and file an issue on ESLint.

Thanks for doing all of that digging!

**Comment by calebeby** [comment]
I have the same issue on a fresh install

**Comment by kentcdodds** [comment]
Could you make a minimal repo to reproduce this?

**Comment by calebeby** [comment]
Yes

**Comment by calebeby** [comment]
https://github.com/calebeby/minimal-eslint-bug

**Comment by kentcdodds** [comment]
Well, in that case, you really don't have an eslint config which is why you are getting this error... You'll need to have a config for eslint.

**Comment by calebeby** [comment]
it's just .eslintrc, right?

**Comment by kentcdodds** [comment]
Yes, properly configuring eslint for your project

**Comment by calebeby** [comment]
OK, I still get the same error as before

**Comment by kentcdodds** [comment]
Hmmm.... I can look into this later. Please feel free to dig if you're able. Could be the same bug that Mark found...
Weird that I've not seen this on my projects...

**Comment by calebeby** [comment]
So when I save `eslint-config-xo` as a devdependency it fixed it. I should've done that earlier, but that raises the question... Why did it not print out the error that it found while parsing the eslint config?

**Comment by kentcdodds** [comment]
Should probably throw the original error.

**Comment by mvolkmann** [comment]
Good suggestion on trying a minimal reproduction! When I trimmed down my .eslintrc.json file, the problem went away. After fixing some issues there, prettier-eslint worked.

Is it supposed to output the content of each JavaScript file it processes?

So why didn't I catch the problem in my .eslintrc.json file sooner? When I run eslint with a bad .eslintrc.json (even something as simple as a missing comma), it responds with a message like "Error: Unexpected string in JSON at position 54". However, when I run prettier-eslint it just says "prettier-eslint [ERROR]: Unable to find config". Maybe prettier-eslint could be modified to output the error message from eslint to make these kinds of issues more obvious.

**Comment by kentcdodds** [comment]
> Maybe prettier-eslint could be modified to output the error message from eslint to make these kinds of issues more obvious.

Yes, definitely. `prettier-eslint-cli` should probably log any thrown errors (right now it just swallows them).

**Comment by kentcdodds** [comment]
Alrighty, this should be improved now. If you want to try it out again, that'd be awesome :)

**Comment by mvolkmann** [comment]
Thanks Kent, works great now!

**Comment by lazamar** [comment]
So, I just fought this same problem and in the end it came down to **missing dependencies** from my `.eslintrc`. 

`prettier-eslint` is not showing eslint dependency errors, it's just ignoring it and saying that it didn't find the configuration. The way I found to debug it was to install `eslint` locally to the project and run it with 

```
node ./node_modules/eslint/bin/eslint.js *.js
```

I had to make sure to use that node invocation otherwise it would use the global eslint instalation and get global packages.

When I ran that, it complained about all the missing dependencies, which after installed made `prettier-eslint` find my `eslintrc` as expected.

**Comment by kentcdodds** [comment]
Thanks for digging further and reporting back! Do you think there's something we could do with logging to make this more obvious when others run into this?

**Comment by lazamar** [comment]
I didn't look into the code, but I assume you have some function `findEslintConfig` that either returns a working config, or nothing. The solutions would be to look into identifying the case that the file is there, but it is not successfully loaded. I believe the same might happen if there are syntax errors in `.eslint`.

I believe once identified, an invalid config should be a showstopper error.

**Comment by kentcdodds** [comment]
Would you be willing to dive in a bit and [make a pull request](http://makeapullrequest.com)?

**Comment by bertho-zero** [comment]
I have the same problem with yarn and enabled workspaces.

The problem is solved by adding `**/prettier-eslint-cli` and `**/prettier-eslint-cli/**`in the `workspaces.nohoist` field.
