### ISSUE TITLE
Different glob results when running via npm script and CLI directly

### ISSUE THREAD

**Issue by pdehaan** [kentcdodds/prettier-eslint-cli#7]
I hacked the ./node_modules/.bin/prettier-eslint-cli/dist/index.js and added an `console.log(argv);` near the bottom, and it's showing some interesting results when running `npm run prettier` in my project, versus just running `./node_modules/.bin/prettier-eslint --single-quote --write src/**/*.js webpack.config.js` directly.

```sh
$ ./node_modules/.bin/prettier-eslint --version # 1.0.3

$ npm run
Scripts available in pulse via `npm run-script`:
  build
    webpack
  lint
    eslint .
  prettier
    prettier-eslint --single-quote --write src/**/*.js webpack.config.js
  watch
    webpack
```

```sh
$ npm run prettier

> pulse@0.1.0 prettier /Users/pdehaan/dev/github/mozilla/pulse
> prettier-eslint --single-quote --write src/**/*.js webpack.config.js

{ _: [ 'src/webextension/background.js', 'webpack.config.js' ],
  h: false,
  help: false,
  version: false,
  'single-quote': true,
  singleQuote: true,
  write: 'src/lib/log.js',
  stdin: false,
  eslintPath: '/Users/pdehaan/dev/github/mozilla/pulse/node_modules/eslint',
  log: false,
  sillyLogs: false,
  '$0': '/Users/pdehaan/dev/github/mozilla/pulse/node_modules/.bin/prettier-eslint',
  prettierPath: undefined }

success formatting 2 files with prettier-eslint
```

When running `npm run prettier` script, it says "success formatting 2 files with prettier-eslint". Oddly, it only finds two files: `[ 'src/webextension/background.js', 'webpack.config.js' ]`

Now, if I run the `./node_modules/.bin/prettier-eslint --single-quote --write src/**/*.js webpack.config.js` script directly, it finds 5 files instead of 2:

```sh
$ ./node_modules/.bin/prettier-eslint --single-quote --write src/**/*.js webpack.config.js
{ _:
   [ 'src/lib/log.js',
     'src/webextension/background.js',
     'src/webextension/survey/lib/open.js',
     'src/webextension/survey/survey.js',
     'webpack.config.js' ],
  h: false,
  help: false,
  version: false,
  'single-quote': true,
  singleQuote: true,
  write: 'src/index.js',
  stdin: false,
  eslintPath: '/Users/pdehaan/dev/github/mozilla/pulse/node_modules/eslint',
  log: false,
  sillyLogs: false,
  '$0': 'node_modules/.bin/prettier-eslint',
  prettierPath: undefined }

success formatting 5 files with prettier-eslint
```

**Comment by kentcdodds** [comment]
Yeah, I've noticed that the globs sometimes don't find quite the right files. I wonder whether you need to have the glob quoted. I think this may be it because [cpy-cli](https://github.com/sindresorhus/cpy-cli) says this:

> <source> can contain globs if quoted

Let me know whether that fixes the issue for you :)

**Comment by kentcdodds** [comment]
Also, if it does, would you mind making an update to the docs to indicate that?

**Comment by pdehaan** [comment]
Sort of works, but is giving me pretty inconsistent results between `prettier` and `prettier-eslint` commands when using quotes. Digging deeper.

### `prettier` (glob w/o quotes) &mdash; finds 3 files?

```sh
$ npm run prettier

> pulse@0.1.0 prettier /Users/pdehaan/dev/github/mozilla/pulse
> prettier --single-quote --write src/**/*.js webpack.config.js

src/webextension/background.js
src/lib/log.js
webpack.config.js
```

### `prettier` (glob w/ quotes) &mdash; finds 6 files?
```sh
$ npm run prettier

> pulse@0.1.0 prettier /Users/pdehaan/dev/github/mozilla/pulse
> prettier --single-quote --write 'src/**/*.js' webpack.config.js

webpack.config.js
src/index.js
src/webextension/background.js
src/lib/log.js
src/webextension/survey/lib/open.js
src/webextension/survey/survey.js
```

### `prettier-eslint` (glob w/o quotes) &mdash; finds 2 files?
```sh
$ npm run prettier

> pulse@0.1.0 prettier /Users/pdehaan/dev/github/mozilla/pulse
> prettier-eslint --single-quote --write src/**/*.js webpack.config.js

[ 'src/webextension/background.js', 'webpack.config.js' ]
The `"useFlowParser": true/false` option is deprecated. Use `parser: "flow"` instead.
The `"useFlowParser": true/false` option is deprecated. Use `parser: "flow"` instead.
success formatting 2 files with prettier-eslint
```

### `prettier-eslint` (glob w/ quotes) &mdash; finds 1 file?
```sh
$ npm run prettier

> pulse@0.1.0 prettier /Users/pdehaan/dev/github/mozilla/pulse
> prettier-eslint --single-quote --write 'src/**/*.js' webpack.config.js

[ 'webpack.config.js' ]
The `"useFlowParser": true/false` option is deprecated. Use `parser: "flow"` instead.
success formatting 1 files with prettier-eslint
```

**Comment by kentcdodds** [comment]
Thanks for that. This is totally weird. Do you suppose you could dig a little deeper to figure out what's going on?

**Comment by pdehaan** [comment]
I'm struggling to find reasons for why, but the temporary workaround seems to be putting the quoted glob first (before the flags). 

### Quoted glob first, 6 files found.
```sh
$ npm run prettier

> pulse@0.1.0 prettier /Users/pdehaan/dev/github/mozilla/pulse
> prettier-eslint 'src/**/*.js' webpack.config.js --single-quote --write

[ 'src/**/*.js', 'webpack.config.js' ]
success formatting 6 files with prettier-eslint
```

### Unquoted glob first, 3 files found.
```sh
$ npm run prettier

> pulse@0.1.0 prettier /Users/pdehaan/dev/github/mozilla/pulse
> prettier-eslint src/**/*.js webpack.config.js --single-quote --write

[ 'src/lib/log.js',
  'src/webextension/background.js',
  'webpack.config.js' ]
success formatting 3 files with prettier-eslint
```

### Unquoted glob last, 2 files found.
```sh
$ npm run prettier

> pulse@0.1.0 prettier /Users/pdehaan/dev/github/mozilla/pulse
> prettier-eslint --single-quote --write src/**/*.js webpack.config.js

[ 'src/webextension/background.js', 'webpack.config.js' ]
success formatting 2 files with prettier-eslint
```

### Quoted glob last, 1 file found.
```sh
$ npm run prettier

> pulse@0.1.0 prettier /Users/pdehaan/dev/github/mozilla/pulse
> prettier-eslint --single-quote --write 'src/**/*.js' webpack.config.js

[ 'webpack.config.js' ]
success formatting 1 files with prettier-eslint
```

**Comment by lydell** [comment]
This might help: https://github.com/jlongster/prettier/issues/362#issuecomment-274250544

**Comment by kentcdodds** [comment]
Oh, that's interesting! We are actually using the glob library. I didn't realize that the terminal tries to expand the glob if it's not quoted. We'll definitely want to update the README for that (anyone wanna [make a PR?](https://github.com/kentcdodds/prettier-eslint-cli/blob/master/CONTRIBUTING.md)).

And we should also figure out why the order of options vs globs matters because it would be nice for people to be able to put those in whatever order they like. We're [using](https://github.com/kentcdodds/prettier-eslint-cli/blob/master/src/parser.js) [yargs](http://yargs.js.org/). If anyone would like to dig into that a little, that would be awesome!

**Comment by kentcdodds** [comment]
I think we've solved this. Please note the docs in the README about quoting globs and update your version to get the latest fixes. Thanks!
